import type { EChartsOption } from 'echarts';
import type * as colors from 'tailwindcss/colors';

export interface WidgetContext<P extends Record<string, any> = Record<string, any>> {
  runtime: 'server' | 'client';
  parameters: P;
}

export interface WidgetVisualizerContext<P extends Record<string, any> = Record<string, any>> extends WidgetContext<P> {
  theme: {
    colors: typeof colors
  };

  /**
   * The container width when executing the visualization function.
   */
  width: number

  /**
   * The container height when executing the visualization function.
   */
  height: number

  getRepo (id: number): any;

  getUser (id: number): any;

  getCollection (id: number): any;

  getOrg (id: number): any;
}

export type EChartsVisualizationConfig = EChartsOption;

export type VisualizeFunction<R, D, P> = (data: D, ctx: WidgetVisualizerContext<P>) => R

export interface WidgetMeta {
  name: string;
  description?: string;
  version: string;
  keywords?: string[];
  author?: string | Partial<{ email: string, name: string, url: string }>;
}

export interface VisualizerModule<Type extends string, VisualizationResult, Data, Params, VisualizerInstance = any> {
  type: Type;
  default: VisualizeFunction<VisualizationResult, Data, Params>;

  /**
   *
   * @param instance instance of visualizer provider. like 'EChartsInstance'
   * @param result last result generated by visualization function
   * @param width new container width
   * @param height new container height
   */
  onSizeChange?: (instance: VisualizerInstance, result: VisualizationResult, width: number, height: number) => void;

  /**
   *
   * @param instance instance of visualizer provider. like 'EChartsInstance'
   * @param result last result generated by visualization function
   * @param colorScheme new color scheme
   */
  onColorSchemeChange?: (instance: VisualizerInstance, result: VisualizationResult, colorScheme: 'light' | 'dark') => void;
}

export interface BaseParameterDefinition {
  type: string;
  title?: string;
  description?: string;
  required: boolean;
  default?: unknown;
}

export interface RepoIdParameterDefinition extends BaseParameterDefinition {
  type: 'repo-id';
}

export type ParameterDefinition = RepoIdParameterDefinition; // | Others;

export type ParameterDefinitions = Record<string, ParameterDefinition>;
