import { SiteBanner } from '@ossinsight/ui/src/components/SiteBanner';
import { SiteHeader } from '@ossinsight/ui/src/components/SiteHeader';
import type { Metadata } from 'next';
import config from '@/site.config';
import './globals.scss';
import Script from 'next/script';
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: [
    '/favicon.png'
  ],
  openGraph: {
    title: 'Widgets List',
    description: 'This project is in development',
    url: 'https://next.ossinsight.io/',
    siteName: 'OSS Insight',
    images: [
      {
        url: '/seo-widgets-homepage.jpeg',
        width: 800,
        height: 600,
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Widgets List',
    description: 'This project is in development',
    creator: '@ossinsight',
    images: ['/seo-widgets-homepage.jpeg'],
  },
};

const GTAG_ID = 'GTM-WBZS43V';

export default function RootLayout ({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body
      // className={inter.className}
    >
    <Script id="google-analytics" src={`https://www.googletagmanager.com/gtag/js?id=${GTAG_ID}`} />
    <Script id="google-analytics-config">
      {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
 
          gtag('config', '${GTAG_ID}');
        `}
    </Script>
    {config.banner && <SiteBanner banner={config.banner} />}
    <SiteHeader {...config.header} />
    {children}
    </body>
    </html>
  );
}
