import { SiteBanner } from '@ossinsight/ui/src/components/SiteBanner';
import { SiteHeader } from '@ossinsight/ui/src/components/SiteHeader';
import type { Metadata } from 'next';
import config from '../site.config';
import './globals.scss';
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: {
    title: 'Widgets List',
    description: 'This project is in development',
    url: 'https://next.ossinsight.io/',
    siteName: 'OSS Insight',
    images: [
      {
        url: '/seo-widgets-homepage.jpeg',
        width: 800,
        height: 600,
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Widgets List',
    description: 'This project is in development',
    creator: '@ossinsight',
    images: ['/seo-widgets-homepage.jpeg'],
  },
};

export default function RootLayout ({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body
      // className={inter.className}
    >
    {config.banner && <SiteBanner banner={config.banner} />}
    <SiteHeader {...config.header} />
    {children}
    </body>
    </html>
  );
}
